// +build !ignore_autogenerated

/*

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// autogenerated by controller-gen object, do not modify manually

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Keto) DeepCopyInto(out *Keto) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Keto.
func (in *Keto) DeepCopy() *Keto {
	if in == nil {
		return nil
	}
	out := new(Keto)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORYAccessControlPolicy) DeepCopyInto(out *ORYAccessControlPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORYAccessControlPolicy.
func (in *ORYAccessControlPolicy) DeepCopy() *ORYAccessControlPolicy {
	if in == nil {
		return nil
	}
	out := new(ORYAccessControlPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ORYAccessControlPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORYAccessControlPolicyList) DeepCopyInto(out *ORYAccessControlPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ORYAccessControlPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORYAccessControlPolicyList.
func (in *ORYAccessControlPolicyList) DeepCopy() *ORYAccessControlPolicyList {
	if in == nil {
		return nil
	}
	out := new(ORYAccessControlPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ORYAccessControlPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORYAccessControlPolicyRole) DeepCopyInto(out *ORYAccessControlPolicyRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORYAccessControlPolicyRole.
func (in *ORYAccessControlPolicyRole) DeepCopy() *ORYAccessControlPolicyRole {
	if in == nil {
		return nil
	}
	out := new(ORYAccessControlPolicyRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ORYAccessControlPolicyRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORYAccessControlPolicyRoleList) DeepCopyInto(out *ORYAccessControlPolicyRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ORYAccessControlPolicyRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORYAccessControlPolicyRoleList.
func (in *ORYAccessControlPolicyRoleList) DeepCopy() *ORYAccessControlPolicyRoleList {
	if in == nil {
		return nil
	}
	out := new(ORYAccessControlPolicyRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ORYAccessControlPolicyRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORYAccessControlPolicyRoleSpec) DeepCopyInto(out *ORYAccessControlPolicyRoleSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]Subject, len(*in))
		copy(*out, *in)
	}
	out.Keto = in.Keto
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORYAccessControlPolicyRoleSpec.
func (in *ORYAccessControlPolicyRoleSpec) DeepCopy() *ORYAccessControlPolicyRoleSpec {
	if in == nil {
		return nil
	}
	out := new(ORYAccessControlPolicyRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORYAccessControlPolicyRoleStatus) DeepCopyInto(out *ORYAccessControlPolicyRoleStatus) {
	*out = *in
	out.ReconciliationError = in.ReconciliationError
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORYAccessControlPolicyRoleStatus.
func (in *ORYAccessControlPolicyRoleStatus) DeepCopy() *ORYAccessControlPolicyRoleStatus {
	if in == nil {
		return nil
	}
	out := new(ORYAccessControlPolicyRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORYAccessControlPolicySpec) DeepCopyInto(out *ORYAccessControlPolicySpec) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]URN, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(map[string]Condition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]URN, len(*in))
		copy(*out, *in)
	}
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]Subject, len(*in))
		copy(*out, *in)
	}
	out.Keto = in.Keto
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORYAccessControlPolicySpec.
func (in *ORYAccessControlPolicySpec) DeepCopy() *ORYAccessControlPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ORYAccessControlPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ORYAccessControlPolicyStatus) DeepCopyInto(out *ORYAccessControlPolicyStatus) {
	*out = *in
	out.ReconciliationError = in.ReconciliationError
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ORYAccessControlPolicyStatus.
func (in *ORYAccessControlPolicyStatus) DeepCopy() *ORYAccessControlPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ORYAccessControlPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconciliationError) DeepCopyInto(out *ReconciliationError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconciliationError.
func (in *ReconciliationError) DeepCopy() *ReconciliationError {
	if in == nil {
		return nil
	}
	out := new(ReconciliationError)
	in.DeepCopyInto(out)
	return out
}
